# Generated by Django 5.1.3 on 2024-12-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('dr', 'Dr.'), ('prof', 'Prof.')], max_length=10, verbose_name='Title')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('course_type', models.CharField(choices=[('society', 'Society'), ('language', 'Language'), ('by_email', 'By Email'), ('by_phone', 'By Phone')], max_length=50, verbose_name='Course Type')),
                ('confirm_type', models.CharField(choices=[('by_phone', 'By Phone'), ('by_email', 'By Email')], max_length=20, verbose_name='Confirmation Type')),
                ('contact_hours', models.CharField(choices=[('8am-10pm', '8am - 10pm'), ('9am-11pm', '9am - 11pm')], max_length=20, verbose_name='Contact Hours')),
                ('agree_terms', models.BooleanField(default=False, verbose_name='Agree to Terms and Conditions')),
            ],
        ),
    ]
