# Generated by Django 5.1.3 on 2025-01-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='confirm_type',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='course_type',
            field=models.CharField(choices=[('programming', 'Programming'), ('data_science', 'Data Science'), ('design', 'Design'), ('marketing', 'Marketing')], max_length=100),
        ),
    ]
