# Generated by Django 5.1.3 on 2025-01-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0002_alter_myuser_confirm_type_alter_myuser_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='contact_hours',
            field=models.CharField(choices=[('1', '1 Hour'), ('2', '2 Hours'), ('3', '3 Hours'), ('4', '4 Hours'), ('5', '5 Hours'), ('6', '6 Hours')], max_length=50),
        ),
    ]
