# Generated by Django 5.1.3 on 2025-01-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0003_alter_myuser_contact_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursescategory',
            name='category',
            field=models.CharField(choices=[('cs_tech', 'Computer Science and Technology'), ('business', 'Business and Commerce'), ('arts_hum', 'Arts and Humanities'), ('sci_math', 'Science and Mathematics'), ('engineering', 'Engineering'), ('health_med', 'Health and Medical'), ('law_gov', 'Law and Governance'), ('misc', 'Miscellaneous')], default='cs', max_length=20),
        ),
        migrations.AddField(
            model_name='coursescategory',
            name='contact_hours',
            field=models.CharField(choices=[('4am-5am', '4:00 AM - 5:00 AM'), ('5am-6am', '5:00 AM - 6:00 AM'), ('6am-7am', '6:00 AM - 7:00 AM'), ('7am-8am', '7:00 AM - 8:00 AM'), ('8am-9am', '8:00 AM - 9:00 AM'), ('9am-10am', '9:00 AM - 10:00 AM'), ('10am-11am', '10:00 AM - 11:00 AM'), ('11am-12pm', '11:00 AM - 12:00 PM'), ('12pm-1pm', '12:00 PM - 1:00 PM'), ('1pm-2pm', '1:00 PM - 2:00 PM'), ('2pm-3pm', '2:00 PM - 3:00 PM'), ('3pm-4pm', '3:00 PM - 4:00 PM'), ('4pm-5pm', '4:00 PM - 5:00 PM'), ('5pm-6pm', '5:00 PM - 6:00 PM'), ('6pm-7pm', '6:00 PM - 7:00 PM'), ('7pm-8pm', '7:00 PM - 8:00 PM'), ('8pm-9pm', '8:00 PM - 9:00 PM'), ('9pm-10pm', '9:00 PM - 10:00 PM'), ('10pm-11pm', '10:00 PM - 11:00 PM'), ('11pm-12am', '11:00 PM - 12:00 AM')], default='8am-12pm', max_length=20),
        ),
        migrations.AddField(
            model_name='coursescategory',
            name='course',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('ai', 'Artificial Intelligence'), ('ml', 'Machine Learning'), ('ds', 'Data Science'), ('web_dev', 'Web Development'), ('app_dev', 'Mobile Application Development'), ('cybersec', 'Cyber Security'), ('ethical_hacking', 'Ethical Hacking'), ('software_dev', 'Software Development'), ('networking', 'Computer Networking'), ('cloud_computing', 'Cloud Computing'), ('iot', 'Internet of Things (IoT)'), ('blockchain', 'Blockchain Technology'), ('devops', 'DevOps'), ('bcom', 'Commerce'), ('mba', 'Master of Business Administration'), ('accounting', 'Accounting and Finance'), ('marketing', 'Marketing'), ('hrm', 'Human Resource Management'), ('entrepreneurship', 'Entrepreneurship'), ('economics', 'Economics'), ('literature', 'English Literature'), ('history', 'History'), ('philosophy', 'Philosophy'), ('psychology', 'Psychology'), ('sociology', 'Sociology'), ('political_science', 'Political Science'), ('linguistics', 'Linguistics'), ('fine_arts', 'Fine Arts'), ('music', 'Music'), ('film_studies', 'Film Studies'), ('design', 'Graphic Design'), ('math', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('geology', 'Geology'), ('statistics', 'Statistics'), ('environmental_science', 'Environmental Science'), ('biotech', 'Biotechnology'), ('astrophysics', 'Astrophysics'), ('mech_eng', 'Mechanical Engineering'), ('civil_eng', 'Civil Engineering'), ('elec_eng', 'Electrical Engineering'), ('elec_comm_eng', 'Electronics and Communication Engineering'), ('chemical_eng', 'Chemical Engineering'), ('aero_eng', 'Aerospace Engineering'), ('biomed_eng', 'Biomedical Engineering'), ('robotics', 'Robotics Engineering'), ('medicine', 'Medicine'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('dentistry', 'Dentistry'), ('physiotherapy', 'Physiotherapy'), ('public_health', 'Public Health'), ('law', 'Law'), ('criminology', 'Criminology'), ('forensics', 'Forensic Science'), ('international_relations', 'International Relations'), ('public_admin', 'Public Administration'), ('education', 'Education'), ('sports_science', 'Sports Science'), ('hospitality', 'Hospitality Management'), ('tourism', 'Tourism and Travel'), ('culinary_arts', 'Culinary Arts'), ('journalism', 'Journalism and Mass Communication'), ('fashion_design', 'Fashion Design'), ('animation', 'Animation'), ('agriculture', 'Agriculture'), ('marine_biology', 'Marine Biology'), ('veterinary', 'Veterinary Science'), ('ai_ml', 'Artificial Intelligence & Machine Learning')], default='computer science', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='course_type',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('ai', 'Artificial Intelligence'), ('ml', 'Machine Learning'), ('ds', 'Data Science'), ('web_dev', 'Web Development'), ('app_dev', 'Mobile Application Development'), ('cybersec', 'Cyber Security'), ('ethical_hacking', 'Ethical Hacking'), ('software_dev', 'Software Development'), ('networking', 'Computer Networking'), ('cloud_computing', 'Cloud Computing'), ('iot', 'Internet of Things (IoT)'), ('blockchain', 'Blockchain Technology'), ('devops', 'DevOps')], max_length=50, verbose_name='Course Type'),
        ),
    ]
