# Generated by Django 5.1.3 on 2024-12-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0004_alter_signup_course_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('course_type', models.CharField(max_length=100)),
                ('confirm_type', models.CharField(max_length=100)),
                ('contact_hours', models.CharField(max_length=50)),
                ('agree_terms', models.BooleanField(default=False)),
            ],
        ),
    ]
