# Generated by Django 5.1.3 on 2025-01-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0006_alter_myuser_contact_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='confirm_type',
            field=models.CharField(choices=[('active', 'Yes'), ('acive', 'No'), ('deffered', 'deffered'), ('suspendend', 'No'), ('suspended', 'yes')], max_length=100),
        ),
    ]
