# Generated by Django 5.1.3 on 2024-12-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0007_remove_testimonial_status_alter_testimonial_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
