# Generated by Django 5.1.3 on 2025-01-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0007_alter_myuser_confirm_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
