# Generated by Django 5.1.3 on 2024-12-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0011_courses_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelance', 'Freelance')], default='Full-time', max_length=20)),
                ('available_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('reviews', models.TextField(blank=True, null=True)),
                ('courses', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='instructors/profile_pictures/')),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
