# Generated by Django 5.1.3 on 2025-01-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0012_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='Course',
            new_name='course',
        ),
    ]
