# Generated by Django 5.1.3 on 2025-01-22 10:34

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0014_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='reg_no',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
