# Generated by Django 5.1.3 on 2024-12-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0017_specialization_remove_instructor_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='courses',
        ),
        migrations.AddField(
            model_name='instructor',
            name='courses',
            field=models.ManyToManyField(related_name='COURSE_CHOICES', to='myschool.signup'),
        ),
    ]
