# Generated by Django 5.1.3 on 2025-01-05 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0021_coursescategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='name',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='courses',
        ),
        migrations.AddField(
            model_name='courses',
            name='coursename',
            field=models.CharField(default='cs', max_length=255, verbose_name='comp'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='course',
            field=models.ManyToManyField(related_name='COURSE_category', to='myschool.coursescategory'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='specialize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myschool.coursescategory'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='coursescategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
