# Generated by Django 5.1.3 on 2024-12-25 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0023_alter_coursescategory_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursescategory',
            name='course',
            field=models.ForeignKey(default='cs', on_delete=django.db.models.deletion.CASCADE, to='myschool.courses'),
        ),
    ]
